version: "3.9" # optional since v1.27.0
services:
  # pypi service with no auth
  pypi:
    image: pypiserver/pypiserver:latest
    ports:
      - "8001:8080"
    volumes:
      - "./packages:/data/packages"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  # docker service with simple auth
  docker:
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - "./registry:/var/lib/registry"
      - "./docker-auth:/auth"
    environment:
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH=htpasswd
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
